title: CV | Vikash Sharma
description:  Digital Profile
url: https://vik4shsh4rma.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
